# Generated by Django 2.2.16 on 2022-02-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20220207_0936'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='unique_slug',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
